apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-register-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-register
  template:
    metadata:
      labels:
        app: msa-register
    spec:
      containers:
        - name: msa-register
          image: docker.io/yoon741/msa_register_service:v1  # 이미지 이름 수정
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret  # Secret 이름
                  key: MYSQL_USER  # Secret 키
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_HOST
              value: "mariadb"
            - name: MYSQL_PORT
              value: "3306"
            - name: CORS_ORIGINS
              value: "http://192.168.56.1:30010,http://front-nodejs-svc:3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-payment-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-payment
  template:
    metadata:
      labels:
        app: msa-payment
    spec:
      containers:
        - name: msa-payment
          image: docker.io/ashashrain/parking-payment-service:v4  # 이미지 이름 수정
          ports:
            - containerPort: 8001
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret  # Secret 이름
                  key: MYSQL_USER  # Secret 키
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_HOST
              value: "mariadb"
            - name: MYSQL_PORT
              value: "3306"
            - name: CORS_ORIGINS
              value: "http://192.168.56.1:30010,http://front-nodejs-svc:3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-product-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-product
  template:
    metadata:
      labels:
        app: msa-product
    spec:
      containers:
        - name: msa-product
          image: docdker/parking  # 이미지 이름 수정
          ports:
            - containerPort: 8002
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret  # Secret 이름
                  key: MYSQL_USER  # Secret 키
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_HOST
              value: "mariadb"
            - name: MYSQL_PORT
              value: "3306"
            - name: CORS_ORIGINS
              value: "http://192.168.56.1:30010,http://front-nodejs-svc:3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-statistics-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-statistics
  template:
    metadata:
      labels:
        app: msa-statistics
    spec:
      containers:
        - name: msa-statistics
          image: snicuz0588/msa-statistics-service:v5  # 이미지 이름 수정
#          image: docdker/statistics:v4
          ports:
            - containerPort: 8003
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret  # Secret 이름
                  key: MYSQL_USER  # Secret 키
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_HOST
              value: "mariadb"
            - name: MYSQL_PORT
              value: "3306"
            - name: CORS_ORIGINS
              value: "http://192.168.56.1:30010,http://front-nodejs-svc:3000"